# Generated by Django 4.2.6 on 2023-12-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='job_number',
            field=models.CharField(default=4726293767, max_length=16),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='salary_range',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='SalaryRange',
        ),
    ]
