# Generated by Django 5.0.2 on 2024-07-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='job_number',
            field=models.CharField(default=7659900963, max_length=16),
        ),
    ]
