INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # "debug_toolbar",
    "corsheaders",
    "rest_framework",
    # 'rest_framework_filters',
    "django_cleanup.apps.CleanupConfig",
    "api",
    "src.system",
    "src.account",
    "src.finance",
    "src.directory",
    "src.recruitment",
    "src.administration",
]
