services:
  hrm:
    container_name: hrm
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5554:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - hrm

  app:
    container_name: app
    restart: always
    build: .
    ports:
      - 8000:8000
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver"
    volumes:
      - .:/app
    depends_on:
      - hrm
