# Generated by Django 5.0.2 on 2024-07-20 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='bank',
            field=models.ForeignKey(blank=True, db_column='staff_bank_name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.bank'),
        ),
        migrations.AddField(
            model_name='staff',
            name='bank_account',
            field=models.ForeignKey(blank=True, db_column='staff_bank_account', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.staffbankaccount'),
        ),
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffdepartment', to='account.department'),
        ),
        migrations.AddField(
            model_name='staff',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.employeegrade'),
        ),
        migrations.AddField(
            model_name='headofdepartment',
            name='hod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hodstaff', to='account.staff'),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='staff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.staff'),
        ),
        migrations.AddField(
            model_name='staff',
            name='work_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.workplace'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['phone_number'], name='staff_phone_number_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['id_number'], name='staff_id_number_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['staff_id'], name='staff_staff_id_idx'),
        ),
    ]
