# Generated by Django 4.2.6 on 2023-12-01 20:59

from django.db import migrations
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=utils.validators.TitleCaseField(default='6670372195321021', max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
