# Generated by Django 4.2.6 on 2023-12-01 22:39

from django.db import migrations
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_staff_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=utils.validators.TitleCaseField(default='9908707593102021', max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
