# Generated by Django 5.0.2 on 2024-07-20 19:47

import utils.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_staff_bank_alter_staff_staff_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='acccess_card',
            new_name='access_card',
        ),
        migrations.AlterField(
            model_name='staff',
            name='middle_name',
            field=utils.validators.TitleCaseField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=utils.validators.TitleCaseField(default='1963441174220270', max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
