# Generated by Django 5.0.2 on 2024-07-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_id',
            field=models.CharField(default='1568947285', max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='formdocument',
            name='form_id',
            field=models.CharField(default='1568947285', max_length=10, primary_key=True, serialize=False, verbose_name='Form ID'),
        ),
        migrations.AlterField(
            model_name='transmital',
            name='transmital_id',
            field=models.CharField(default='156894728512', max_length=16, primary_key=True, serialize=False),
        ),
    ]
