# Generated by Django 5.0.2 on 2024-07-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_alter_document_document_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_id',
            field=models.CharField(default='2746051174', max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='formdocument',
            name='form_id',
            field=models.CharField(default='2746051174', max_length=10, primary_key=True, serialize=False, verbose_name='Form ID'),
        ),
        migrations.AlterField(
            model_name='transmital',
            name='transmital_id',
            field=models.CharField(default='274605117422', max_length=16, primary_key=True, serialize=False),
        ),
    ]
