# Generated by Django 4.2.6 on 2023-12-01 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_staff_staff_id'),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('Commendation', 'Commendation'), ('Criticism', 'Criticism'), ('Suggestion', 'Suggestion'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.staff'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_id',
            field=models.CharField(default=337117503318, max_length=12),
        ),
    ]
