# Generated by Django 5.0.2 on 2024-07-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_id',
            field=models.CharField(default=714363453460, max_length=12),
        ),
        migrations.AlterField(
            model_name='trainingfile',
            name='resouce_id',
            field=models.CharField(default='825545728512', max_length=16),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='resouce_id',
            field=models.CharField(default='825545728512', max_length=16),
        ),
    ]
