# Generated by Django 4.2.6 on 2023-12-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_feedback_feedback_type_alter_feedback_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_id',
            field=models.CharField(default=923325414542, max_length=12),
        ),
    ]
