# Generated by Django 5.0.2 on 2024-07-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_survey_survey_id_alter_trainingfile_resouce_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_id',
            field=models.CharField(default=522629425680, max_length=12),
        ),
        migrations.AlterField(
            model_name='trainingfile',
            name='resouce_id',
            field=models.CharField(default='160355117422', max_length=16),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='resouce_id',
            field=models.CharField(default='160355117422', max_length=16),
        ),
    ]
